import {
  ChesLogo,
  SVNITLOGO,
  aiche_logo,
  SIPHON,
  Workshop,
  car,
  K12,
  uphoto,
  Alchemy,
  aa,
  ab,
  ac,
  ad,
  ae,
  af,
  ag,
  Alchemylogo,
  SIPHONlogo,
  Workshoplogo,
  K12logo,
  Eurekalogo,
  car_logo,
  SRClogo,
  SRC,
  Archit,
  Kamakshi,
  Bhumi,
  Yukta,
  Technical,
  ayushi,
  gaurav,
  mahendra,
  president,
  priyal,
  sahil,
  sambhavi,
  swapnil,
  sheetal,
  shipra,
  sarrah,
  anuj,
  ayush,
  himanshu,
  himil,
  nisarg,
  pranav,
  ronak,
  vrund,
  kenny,
  neha,
  sajal,
  sayantani,
  tanay,
  utsav,
  aswin,
  devsharma,
  dheypatel,
  dhyeybhagat,
  kushal,
  rupesh,
  sarita,
  simran,
  soumya,
  namrata,
  aneCar,
  alluCar,
  aditya,
  abhay,
  abhishek,
  shikhar,
  vivek,
  kunal,
  sapan,
  abhaydubey,
  bhuvan,
  chaitnya,
  harshnath,
  manisha,
  pranali,
  pruthvi,
  ravindra,
  surajsingh,
  khirabdhi,
  alisha,
  akshat,
  sondarva,
  aishwarya,
  jugal,
  salonee,
  surbhi,
  dhananjay,
  kaveri,
  atharva,
  nisha,
  priyansu,
  vrushti,
  harish,
  deval,
  shrushti,
  vaishvik,
  ChesNoText,
  Himanshu2425,
  Rahul2425,
  chemTeam24_1,
  chemTeam24_2,
  chemTeam24_3,
  chemTeam24_4,
  chemTeam24_5,
  dolly,
  navneet,
  Palak,
  Yatharth,
} from "@/public/assets";

export const NavLinks = [
  {
    id: "/",
    title: "Home",
  },
  {
    id: "/#About",
    title: "About",
  },
  {
    id: "/Events",
    title: "Events",
  },
  {
    id: "/Achievement",
    title: "Achievements",
  },
  {
    id: "/Team",
    title: "Team",
  },

  {
    id: "/contact",
    title: "Contact",
  },
];

export const Developers = [
  {
    position: "Head",
    name: "Archit Kulshrestha",
    Linkedin: "https://www.linkedin.com/in/archit-kulshrestha-1aa01a255/",
    ImageUrl: Archit,
  },
  {
    position: "Executive",
    name: "Abhay Dubey",
    Linkedin: "https://www.linkedin.com/in/abhay-dubey-480a48264/",
    ImageUrl: abhay,
  },
  {
    position: "Executive",
    name: "Aditya Kumar",
    Linkedin: "https://www.linkedin.com/in/adityak1911/",
    ImageUrl: aditya,
  },
  {
    position: "Executive",
    name: "Shikhar Shukla",
    Linkedin: "https://www.linkedin.com/in/shikhar-shukla-011062256/",
    ImageUrl: shikhar,
  },
  {
    position: "Executive",
    name: "Vivek Prasad",
    Linkedin: "https://www.linkedin.com/in/vivek-prasad-che/",
    ImageUrl: vivek,
  },
  {
    position: "Executive",
    name: "Abhishek Sharma",
    Linkedin: "https://www.linkedin.com/in/abhishek-sharma-38b97125b/",
    ImageUrl: abhishek,
  },

  {
    position: "Member",
    name: "Kamakshi Jibhkate",
    Linkedin: "https://www.linkedin.com/in/kamakshi-jibhkate-35671529a/",
    ImageUrl: Kamakshi,
  },
  {
    position: "Member",
    name: "Bhumi Gupta",
    Linkedin: "https://www.linkedin.com/in/bhumi-gupta-b13b1528a/",
    ImageUrl: Bhumi,
  },

  {
    position: "Member",
    name: "Namrata Patil",
    Linkedin: "https://www.linkedin.com/in/namrata-patil-220714282/",
    ImageUrl: namrata,
  },
  {
    position: "Member",
    name: "Yatharth Neel",
    Linkedin: "http://www.linkedin.com/in/yatharth-neel-63706a332",
    ImageUrl: Yatharth,
  },
  {
    position: "Member",
    name: "Palak Singh",
    Linkedin: "https://www.linkedin.com/in/palak-singh-a397b9369",
    ImageUrl: Palak,
  },
  {
    position: "Member",
    name: "Navneet Yadav",
    Linkedin: "https://www.linkedin.com/in/navneet-yadav-884b0031b",
    ImageUrl: navneet,
  },
  {
    position: "Member",
    name: "Dolly Sharma",
    Linkedin: "https://www.linkedin.com/in/dolly-sharma-498b7038a",
    ImageUrl: dolly,
  },
];
export const AluMillennium = {
  name: "AluMillennium",
  img: alluCar,
  design:
    "The vehicle in question employs a front-wheel drive system, wherein the power is transmitted to the front wheels. This propulsion mechanism is facilitated by the utilization of aluminum air cells, which are interconnected through a series and parallel configuration. The electrical energy generated by these air cells is then converted into mechanical energy through the utilization of a motor. This motor, in turn, drives the rotation of the wheel via a two-gear system, enabling the efficient transfer of power and the subsequent movement of the vehicle.",
  powerSource:
    "The power source utilized in this system is an Aluminum-Air Battery, which features copper electrodes connected to the aluminum components. The core structure of the cell is composed of aluminum sheets. The space between the two electrode layers is filled with a specialized material that serves a critical function within the device's overall design and operation. Potassium hydroxide (KOH) solution serves as the electrolyte. A graphite sheet coated with a paste containing activated charcoal and manganese dioxide (MnO2) functions as the cathode. Steel mesh is also attached with a cathode as a current collector. These elements are assembled together using adhesive tape, and the individual cells are connected in various series and parallel configurations to achieve the desired voltage and current output. The stacking of these electrochemical cells is facilitated through the use of an enclosure fabricated from acrylic sheets, providing a robust and organized housing for the complete power generation system.",
  stoppingMechanism:
    "The Iodine Clock is used as a stopping mechanism. Two solutions namely A and B are produced. Solution A contains fixed proportions of Starch, Water and Hydrogen Peroxide while Solution B contains fixed proportions of powdered Vitamin C, water at 323K and Iodine. These two solutions are mixed together in order to form a timed reaction",
};

export const Anerobes = {
  name: "Anerobes",
  img: aneCar,
  design:
    "The car is mounted upon by a lead-acid battery of dimension 10cm*6.5cm*7.5 cm. The battery is charged via the Microbial Fuel Cells (MFCs) that powers the chem-e-car. The stopping mechanism consists of Arduino and a beaker of 50 mL where the stopping reaction takes place.",
  powerSource:
    "Microbial Fuel Cells (MFCs) generate electricity by utilizing anaerobic bacteria to oxidize organic matter, releasing electrons. These electrons flow through an external circuit from the anode to the cathode, where they combine with protons which passes through proton exchange membrane and oxygen to form water, completing the electrochemical circuit.This continuous electron flow generates a steady electric current, which can be harnessed to power electrical devices or stored for later use. Although MFCs provide sustainable energy, they generate low and fluctuating power. To power the Chem-E-Car, this energy is stored in a lead-acid battery, which provides a stable, continuous output. The lead-acid battery is charged by the MFC using a diode switch or power management system(PMS), ensuring sufficient power to run the car.",
  stoppingMechanism:
    "The stopping mechanism involves a reaction between sodium thiosulfate (Na₂S₂O₃) and hydrochloric acid (HCl), which produces sodium chloride, sulfur, sulfur dioxide, and water. As the reaction progresses, the formation of colloidal sulfur increases the solution’s turbidity, reducing the intensity of light transmitted through the mixture. This change is detected by a sensor, which sends a signal to an Arduino that stops the car’s circuit. The reaction's time vs. concentration graph helps determine the stopping time.",
};

export const Anerobes2024 = {
  name: "Anerobes2024",
  img: chemTeam24_4,
  design:
    "The car is powered directly by 8 Microbial Fuel Cell stacks, eliminating the need for an external battery source. The MFC stacks act as the primary energy unit, generating electricity through biochemical processes to fuel the Chem-E-Car. The stopping mechanism is Arduino-based, utilizing a sulfur clock reaction to precisely control the car’s halt. This reaction-driven approach ensures accurate timing and chemical kinetics control.",
  powerSource:
    "Microbial Fuel Cells (MFCs) generate electricity by utilizing anaerobic bacteria to oxidize organic matter, releasing electrons. These electrons flow through an external circuit from the anode to the cathode, where they combine with protons which passes through proton exchange membrane and oxygen to form water, completing the electrochemical circuit.This continuous electron flow generates a steady electric current, which can be harnessed to power electrical devices or stored for later use. Although MFCs provide sustainable energy, they generate low and fluctuating power. To power the Chem-E-Car, this energy is stored in a lead-acid battery, which provides a stable, continuous output. The lead-acid battery is charged by the MFC using a diode switch or power management system(PMS), ensuring sufficient power to run the car.",
  stoppingMechanism:
    "The stopping mechanism involves a reaction between sodium thiosulfate (Na₂S₂O₃) and hydrochloric acid (HCl), which produces sodium chloride, sulfur, sulfur dioxide, and water. As the reaction progresses, the formation of colloidal sulfur increases the solution’s turbidity, reducing the intensity of light transmitted through the mixture. This change is detected by a sensor, which sends a signal to an Arduino that stops the car’s circuit. The reaction's time vs. concentration graph helps determine the stopping time.",
};

export const Batch1920 = [
  {
    position: "President",
    name: "Chaitanya Bhimrajka",
    ImageUrl: chaitnya,
    linkedin: "https://www.linkedin.com/in/chaitanya-bhimrajka-61644974",
  },
  {
    position: "Vice President",
    name: "Abhay Dubey",
    ImageUrl: abhaydubey,
    linkedin: "https://www.linkedin.com/in/abhay-dubey-4626bb145/",
  },
  {
    position: "Managerial",
    name: "Tarang Desai",
    // ImageUrl: tarang,
    linkedin: "",
  },
  {
    position: "Technical Secretary",
    name: "Swapnil Bhavsar",
    ImageUrl: swapnil,
    linkedin: "https://www.linkedin.com/in/swapnil-bhavsar",
  },
  {
    position: "PUBLICITY",
    name: "Anuj sawal",
    ImageUrl: anuj,
    linkedin: "https://www.linkedin.com/in/anuj-sawal-spjimr",
  },
  {
    position: "Documentation",
    name: "Sambhavi Shrivastav",
    ImageUrl: sambhavi,
    linkedin: "",
  },
];

export const Batch1819 = [
  {
    position: "President",
    name: "Khirabdhi Mohanty",
    ImageUrl: khirabdhi,
    linkedin:
      "https://www.linkedin.com/in/khirabdhi-tannaya-mohanty-00402b169/",
  },
  {
    position: "Vice President",
    name: "Alisha Chakraborty",
    ImageUrl: alisha,
    linkedin: "https://www.linkedin.com/in/alisachakraborty/",
  },
  {
    position: "Treasurer",
    name: "Chaitanya Bhimrajka",
    ImageUrl: chaitnya,
    linkedin: "https://www.linkedin.com/in/chaitanya-bhimrajka-61644974",
  },
  {
    position: "Managerial Secretary",
    name: "Abhay Dubey",
    ImageUrl: abhaydubey,
    linkedin: "",
  },
  {
    position: "Technical Secretary",
    name: "Siraj Deraiya",
    // ImageUrl: siraj,
    linkedin: "/Team/Batch1819",
  },
];

export const Batch1718 = [
  {
    position: "President",
    name: "Akshat Ghiya",
    ImageUrl: akshat,
    linkedin: "https://www.linkedin.com/in/akshat-ghiya",
  },
  {
    position: "Vice President",
    name: "Ravindra Shah Singh",
    ImageUrl: ravindra,
    linkedin: "https://www.linkedin.com/in/ravindershahsingh/",
  },
  {
    position: "Treasurer",
    name: "Khirabdhi Mohanty",
    ImageUrl: khirabdhi,
    linkedin:
      "https://www.linkedin.com/in/khirabdhi-tannaya-mohanty-00402b169/",
  },
  {
    position: "Secretary",
    name: "Manish Mazumder",
    ImageUrl: manisha,
    linkedin: "https://www.linkedin.com/in/manishamazumdar25",
  },
  {
    position: "Technical Secretary",
    name: "Kalpesh Sondarva",
    ImageUrl: sondarva,
    linkedin: "https://www.linkedin.com/in/sondarva-kalpesh-38282b117",
  },
  {
    position: "Social Media Secretary",
    name: "Aishwarya Menon",
    ImageUrl: aishwarya,
    linkedin: "https://www.linkedin.com/in/aiswarya-menon-866486154",
  },
];

export const Batch1617 = [
  {
    position: "President",
    name: "Pranali Dandekar",
    ImageUrl: pranali,
    linkedin: "https://www.linkedin.com/in/pranali-dandekar-08b686105",
  },
  {
    position: "Secretary",
    name: "Bhuvan Shah",
    ImageUrl: bhuvan,
    linkedin: "https://www.linkedin.com/in/bhuvan-shah-332a9b9b",
  },
  {
    position: "Treasurer",
    name: "Akshat Ghiya",
    ImageUrl: akshat,
    linkedin: "https://www.linkedin.com/in/akshat-ghiya",
  },
  {
    position: "Managerial Secretary",
    name: "Salonee Goud",
    ImageUrl: salonee,
    linkedin: "https://www.linkedin.com/in/salonee-goud",
  },
  {
    position: "Technical Secretary",
    name: "Jugal Dave",
    ImageUrl: jugal,
    linkedin: "https://www.linkedin.com/in/jugal-dave-63b338b7",
  },
];

export const Batch1516 = [
  {
    position: "President",
    name: "Suraj Singh Dixit",
    ImageUrl: surajsingh,
    linkedin: "https://www.linkedin.com/in/suraj-singh-dixit-71bab09a",
  },
  {
    position: "Vice President",
    name: "Harsh Nath",
    ImageUrl: harshnath,
    linkedin: "https://www.linkedin.com/in/harshnath",
  },
  {
    position: "Treasurer",
    name: "Rishabh Sambaria",
    // ImageUrl: rishabh,
    linkedin: "/Team/Batch1516",
  },
  {
    position: "Secretary",
    name: "Kaveri Sharma",
    ImageUrl: kaveri,
    linkedin: "https://www.linkedin.com/in/kaveri-sharma-950148b6",
  },
  {
    position: "Secretary",
    name: "Dhananjay Joshi",
    ImageUrl: dhananjay,
    linkedin: "https://www.linkedin.com/in/dhananjay-joshi/",
  },
];

export const Batch1415 = [
  {
    position: "Founder",
    name: "Kunal Singh",
    ImageUrl: kunal,
    linkedin: "https://www.linkedin.com/in/kunal-singh-ai ",
  },
  {
    position: "Co-Founder",
    name: "Sapan Gandhi",
    ImageUrl: sapan,
    linkedin: "https://www.linkedin.com/in/sapan-gandhi ",
  },
  {
    position: "Co-Founder",
    name: "Surabhi Prasad",
    ImageUrl: surbhi,
    linkedin: "https://www.linkedin.com/in/surbhi-prasad ",
  },
];

export const Batch2021 = [
  {
    position: "PRESIDENT",
    name: "Javed Alam Saifi",
    ImageUrl: president,
    linkedin: "https://www.linkedin.com/in/jas-chemistry",
  },
  {
    position: "VICE-PRESIDENT",
    name: "Shambhavi Srivastava",
    ImageUrl: sambhavi,
    linkedin: "/Team/Batch2021",
  },
  {
    position: "Advisor",
    name: "Sarrah Saify",
    ImageUrl: sarrah,
    linkedin: "https://www.linkedin.com/in/sarrah-saify-engineer",
  },
  {
    position: "SECRETARY",
    name: "Yukta Malik",
    ImageUrl: Yukta,
    linkedin: "https://www.linkedin.com/in/yukta-malik-408490145",
  },
  {
    position: "SECRETARY",
    name: "Swapnil Bhavsar",
    ImageUrl: swapnil,
    linkedin: "https://www.linkedin.com/in/swapnil-bhavsar",
  },
  {
    position: "SECRETARY(Treasurer)",
    name: "Gaurav Tayade",
    ImageUrl: gaurav,
    linkedin: "https://www.linkedin.com/in/gaurav-tayade-a512ab158",
  },
  {
    position: "MANAGERIAL",
    name: "Mahendra Singh",
    ImageUrl: mahendra,
    linkedin: "https://www.linkedin.com/in/mahendra-singh-5859561a1",
  },
  {
    position: "TECHNICALL",
    name: "Paavan Rupapara",
    ImageUrl: Technical,
    linkedin: "https://www.linkedin.com/in/paavan-rupapara",
  },
  {
    position: "Innovation head",
    name: "Sheetal Maheshwari",
    ImageUrl: sheetal,
    linkedin: "https://www.linkedin.com/in/sheetal-maheshwari-24a211190",
  },
  {
    position: "SOCIAL MEDIA",
    name: "Shipra Novil",
    ImageUrl: shipra,
    linkedin: "https://www.linkedin.com/in/shipranovil",
  },
  {
    position: "WEB D",
    name: "Sahil Shahi",
    ImageUrl: sahil,
    linkedin: "https://www.linkedin.com/in/sahilrajiv",
  },
  {
    position: "DOCUMENTATION",
    name: "Aayushi Gupta",
    ImageUrl: ayushi,
    linkedin: "https://www.linkedin.com/in/aayushi-gupta-aayushi22",
  },
  {
    position: "DOCUMENTATION",
    name: "Priyal Panda",
    ImageUrl: priyal,
    linkedin: "https://www.linkedin.com/in/priyal-panda-960883204",
  },
];

export const Batch2122 = [
  {
    position: "PRESIDENT",
    name: "Sheetal Maheshwari",
    ImageUrl: sheetal,
    linkedin: "https://www.linkedin.com/in/sheetal-maheshwari-24a211190",
  },
  {
    position: "VICE-PRESIDENT",
    name: "Shipra Novil",
    ImageUrl: shipra,
    linkedin: "https://www.linkedin.com/in/shipranovil",
  },
  {
    position: "Student Advisor",
    name: "Aayushi Gupta",
    ImageUrl: ayushi,
    linkedin: "https://www.linkedin.com/in/aayushi-gupta-aayushi22",
  },
  {
    position: "Committee Coordinator",
    name: "Ronak Asnani",
    ImageUrl: ronak,
    linkedin: "https://www.linkedin.com/in/ronak-asnani-40bb311a6",
  },
  {
    position: "Treasurer",
    name: "Nisarg Shah",
    ImageUrl: nisarg,
    linkedin: "https://www.linkedin.com/in/nisarg-shah2001",
  },
  {
    position: "MANAGERIAL",
    name: "Himil Gohel",
    ImageUrl: himil,
    linkedin: "https://www.linkedin.com/in/himilgohel",
  },
  {
    position: "TECHNICALL",
    name: "Vrund Shah",
    ImageUrl: vrund,
    linkedin: "https://www.linkedin.com/in/vrund-shah-b44a36193",
  },
  {
    position: "PUBLIC RELATIONS",
    name: "Ayush Biyani",
    ImageUrl: ayush,
    linkedin: "https://www.linkedin.com/in/ayush-biyani",
  },
  {
    position: "SOCIAL MEDIA",
    name: "Himanshu Gaikwad",
    ImageUrl: himanshu,
    linkedin: "https://www.linkedin.com/in/himanshu-gaikwad-b8638b1b1",
  },
  {
    position: "WEB D",
    name: "Pranav Dherange",
    ImageUrl: pranav,
    linkedin: "https://www.linkedin.com/in/pranav-dherange-251b101a7",
  },

  {
    position: "DOCUMENTATION ",
    name: "Bhumika Sharma",

    linkedin: "https://www.linkedin.com/in/bhumika-sharma-0837141b9",
  },
  {
    position: "DESIGN",
    name: "Kushagra Gupta",

    linkedin: "https://www.linkedin.com/in/kushagragupta3307",
  },
];

export const Batch2223 = [
  {
    position: "PRESIDENT",
    name: "Himanshu Gaikwaid",
    ImageUrl: himanshu,
    linkedin: "http://www.linkedin.com/in/himanshu-gaikwad-b8638b1b1",
  },
  {
    position: "VICE-PRESIDENT",
    name: "Kushagra Gupta",
    linkedin: "https://www.linkedin.com/in/kushagragupta3307",
  },
  {
    position: "TREASURER ",
    name: "Dhyey Bhagat",
    ImageUrl: dhyeybhagat,
    linkedin: "https://www.linkedin.com/in/dhyey-bhagat-a36599215",
  },
  {
    position: "MANAGERIAL",
    name: "Prashant Paliwal",
    linkedin: "https://www.linkedin.com/in/prashant-paliwal-20080121a/",
  },
  {
    position: "TECHNICAL",
    name: "Dhyey Patel",
    ImageUrl: dheypatel,
    linkedin: "/Team/Batch2223",
  },
  {
    position: "K12 OUTREACH",
    name: "Bollineni Neha",
    ImageUrl: neha,
    linkedin: "https://www.linkedin.com/in/bollineni-neha-a22319202/",
  },
  {
    position: "PUBLIC RELATIONS",
    name: "Abhyudayam Dadhich",
    linkedin: "https://www.linkedin.com/in/abhyudaya-dadhich-712916205/",
  },
  {
    position: "DESIGN",
    name: "Sajal Saxena",
    ImageUrl: sajal,
    linkedin: "https://www.linkedin.com/in/sajalsaxena20/",
  },
  {
    position: "DESIGN",
    name: "Tanay Damania",
    ImageUrl: tanay,
    linkedin: "https://www.linkedin.com/in/tanay-damania-22374221a",
  },
  {
    position: "SOCIAL MEDIA",
    name: "Sayantani Dutta",
    ImageUrl: sayantani,
    linkedin: "https://www.linkedin.com/in/sayantanidutta25",
  },
  {
    position: "PUBLICITY",
    name: "Utsav Singh",
    ImageUrl: utsav,
    linkedin: "https://www.linkedin.com/in/utsavsingh18/",
  },
  {
    position: "DOCUMENTATION",
    name: "Kenny Kachhadiya",
    ImageUrl: kenny,
    linkedin: "https://www.linkedin.com/in/kenny-kachhadiya-7a047021a/",
  },
];

export const Batch2324 = [
  {
    position: "PRESIDENT",
    name: "Dhyey  Bhagat",
    ImageUrl: dhyeybhagat,
    linkedin: "https://www.linkedin.com/in/dhyey-bhagat-a36599215",
  },
  {
    position: "VICE-PRESIDENT",
    name: "Dhyey Patel",
    ImageUrl: dheypatel,
    linkedin: "/Team/Batch2324",
  },
  {
    position: "MANAGERIAL",
    name: "Aswin Nair",
    ImageUrl: aswin,
    linkedin: "https://www.linkedin.com/in/aswin-nair-750b22222",
  },
  {
    position: "TECHNICAL",
    name: "Dev Sharma",
    ImageUrl: devsharma,
    linkedin: "https://www.linkedin.com/in/dev-sharma-4b8b52150",
  },
  {
    position: "K12 OUTREACH",
    name: "Rupesh Yadav",
    ImageUrl: rupesh,
    linkedin: "https://www.linkedin.com/in/rupesh-yadav-3440ba22a/",
  },
  {
    position: "PUBLIC RELATIONS",
    name: "Saumya Jain",
    ImageUrl: soumya,
    linkedin: "https://www.linkedin.com/in/saumya-jain-183-/",
  },
  {
    position: "DESIGN",
    name: "Ranjana Soni",
    linkedin: "https://www.linkedin.com/in/ranjana-soni-92b53821b/",
  },
  {
    position: "SOCIAL MEDIA",
    name: "Simran Hirekhan",
    ImageUrl: simran,
    linkedin: "https://www.linkedin.com/in/simran-hirekhan-300532254/",
  },
  {
    position: "FINANCE",
    name: "Kushal Doshi",
    ImageUrl: kushal,
    linkedin: "https://www.linkedin.com/in/kushal-doshi-033569241/",
  },
  {
    position: "FINANCE",
    name: "Om Pandey",
    linkedin: "https://www.linkedin.com/in/om-pandey21/",
  },
  {
    position: "EDITORIAL",
    name: "Nitin Vaishnav",
    linkedin: "https://www.linkedin.com/in/nitin-vaishnav-521a79251/",
  },
  {
    position: "DOCUMENTATION",
    name: "Sarita Meena",
    ImageUrl: sarita,
    linkedin: "https://www.linkedin.com/in/sarita-meena-6b1bba227",
  },
];

export const Batch2425 = [
  {
    position: "President",
    name: "Dev Sharma",
    ImageUrl: devsharma,
    linkedin: "https://www.linkedin.com/in/dev-sharma-4b8b52150",
  },
  {
    position: "Vice-President",
    name: "Aswin Nair",
    ImageUrl: aswin,
    linkedin: "https://www.linkedin.com/in/aswin-nair-750b22222",
  },
  {
    position: "Secretary",
    name: "Sarita Meena",
    ImageUrl: sarita,
    linkedin: "https://www.linkedin.com/in/sarita-meena-6b1bba227",
  },
  {
    position: "Secretary",
    name: "Kushal Doshi",
    ImageUrl: kushal,
    linkedin: "https://www.linkedin.com/in/kushal-doshi-033569241",
  },
  {
    position: "Managerial",
    name: "Priyansu Prajapati",
    ImageUrl: priyansu,
    linkedin: "https://www.linkedin.com/in/priyansu-prajapati-8b5166258",
  },
  {
    position: "Technical",
    name: "Himanshu Singh",
    ImageUrl: Himanshu2425,
    linkedin: "https://www.linkedin.com/in/himanshu-singh-319747263",
  },
  {
    position: "K12 Outreach",
    name: "Vrushti Patel",
    ImageUrl:  vrushti,
    linkedin: "https://www.linkedin.com/in/vrushti-patel-a63819262",
  },
  {
    position: "Public Relations",
    name: "Deval Mehta",
    ImageUrl: deval,
    linkedin: "https://www.linkedin.com/in/deval-mehta-59652b254",
  },
  {
    position: "Design",
    name: "Atharva Tajane",
    ImageUrl: atharva,
    linkedin: "https://www.linkedin.com/in/atharva-tajane",
  },
  {
    position: "Social Media",
    name: "Shrushti Meshram",
    ImageUrl: shrushti,
    linkedin: "https://www.linkedin.com/in/shrushti-meshram-ba3b7a290",
  },
  {
    position: "Finance",
    name: "Vaishvik Kothia",
    ImageUrl: vaishvik,
    linkedin: "https://www.linkedin.com/in/vaishvik-kothia",
  },
  {
    position: "Web Development",
    name: "Archit Kulshrestha",
    ImageUrl: Archit,
    linkedin: "https://www.linkedin.com/in/archit-kulshrestha-1aa01a255",
  },
  {
    position: "Editorial",
    name: "Rahul Choudhary",
    ImageUrl: Rahul2425,
    linkedin: "https://www.linkedin.com/in/rahul-choudhary-ch52",
  },
  {
    position: "Documentation",
    name: "Nisha Sinha",
    ImageUrl: nisha,
    linkedin: "https://www.linkedin.com/in/nisha1304",
  },
  {
    position: "Publicity",
    name: "Harish Khandelwal",
    ImageUrl: harish,
    linkedin: "https://www.linkedin.com/in/harish-khandelwal-a247b7255",
  },
];
